name: NewApp
description: A new social media for going out to the bars


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  strings: ^0.2.1
  image_picker: ^0.7.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: "^8.0.0"
  jiffy: ^4.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - assets/img/
  
  fonts:
    - family: Hindsiliguri
      fonts:
        - asset: fonts/Hindsiliguri-Regular.ttf
        - asset: fonts/Hindsiliguri-Bold.ttf
          weight: 700
    - family: CrimsonText
      fonts:
        - asset: fonts/CrimsonText-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
        - asset: fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: fonts/Merriweather-Italic.ttf
          style: italic
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: fonts/Oxygen-Regular.ttf
  

  